mim/cli.py

Abbr works if it's the prefix of only one sub_command. 
For example, `mim g` stands for `mim gridsearch`.

[Feature] Support abbr of sub_command name

---

mim/commands/gridsearch.py
mim/commands/run.py
mim/commands/test.py
mim/commands/train.py
mim/utils/__init__.py
mim/utils/utils.py

1. Add abbreviations to mim sub-commands: train, test, gridsearch
2. Sub-commands train, test, run, gridsearch can accept abbreviations of package names as long as the abbrev is a substring of one (and only one) package name.

[Improvement] Shorten mim commands

---

mim/commands/install.py
tests/test_install.py

```shell
>>> git clone https://github.com/open-mmlab/mmclassification.git
>>> cd mmclassification
```
If we type "mim install mmcls" in the current directory (mmclassification), it will raise an exception before the PR because it wrongly confirms `os.abspath('mmcls')` is a valid path. However, our intention is to install mmcls from a remote source.
If so, please describe how it breaks the compatibility and how the downstream …

[Fix] Fix install ambiguous

---

mim/utils/default.py

Fix the bug that failed to obtain  os.environ['HOME'] in windows.
1. Pre-commit or other linting tools are used to …

[Fix] Fix home dir error in windows

---

mim/commands/gridsearch.py
mim/commands/test.py
mim/commands/train.py

If mim finds a config file in the codebase, it will show the file path. But now it will show a link path, for example:
```
The path resnet18_b16x8_cifar10.py doesn't exist but we find the config file in codebase mmcls, will use /home/xxx/mmclassification/mmcls/.mim/configs/resnet/resnet18_b16x8_cifar10.py instead.
```
Show the real path instead of the symbolic path. like
```
The path resnet18_b16x8_cifar10.py doesn't exist but we find the config file in codebase mmcls, will use /home/xxx/mmclassification/configs/resnet/resnet18_b16x8_cifar10.py instead.
```

[Fix] Show the real path when use an alternative config file

---

mim/commands/gridsearch.py
mim/commands/test.py
mim/commands/train.py
mim/utils/utils.py

mim will search config files from the codebase if the config path does not exist.
But by default `os.walk` won't follow links, and `pkg/.mim/configs` is a symbolic link to the real config folder. So this search does not work in fact.
Add `followlinks` option in `recursively_find`, and use it when searching config files.
In addition, now mim will search `pkg/.mim/configs` if it exists, instead of search the whole package root directly.

[Fix] Fix config search when train, test and gridsearch

---

mim/commands/gridsearch.py

Fix the bug: When the default value of an argument is 0,  the `gridsearch` command gets the wrong type of the corresponding argument to search.

[Fix] TypeError of gridsearch command

---

mim/commands/install.py

With pip==22.1 command `min install X` produces the following error:
```
#38 7.318 Usage:   
#38 7.318   /opt/conda/bin/python -m pip install [options] <requirement specifier> [package-index-options] ...
#38 7.318   /opt/conda/bin/python -m pip install [options] -r <requirements file> [package-index-options] ...
#38 7.318   /opt/conda/bin/python -m pip install [options] [-e] <vcs project url> ...
#38 7.318   /opt/conda/bin/python -m pip install [options] [-e] <local project path> ...
#38 7.318   /opt/conda/bin/python -m pip install [options] <archive url/path> ...
#38 7.318 
#38 7.318 option --use-feature: invalid choice: 'in-tree-build' (choose from '2020-resolver', 'fast-deps')
#38 7.380 Traceback (most recent call last):
#38 7.380   File …
```

mim install does not work with pip >= 22.1

---

requirements.txt
setup.py

Add extra dependencies to extra_require.
- Add requirements.txt.
- Update setup.py.
No …

Add extra dependencies to extra_require

---

mim/commands/install.py
mim/utils/__init__.py
mim/utils/default.py

Add `MMCV_FIND_BASE_URL` environment variable to support customize mmcv find link.
- mim/commands/install.py
-  mim/utils/default.py
- mim/utils/\_\_init\_\_.py
```Bash
>  MMCV_BASE_URL=https://download.openmmlab.com mim install mmcv-full
```
1. Pre-commit or other linting tools are …

[Feat] Add MMCV_BASE_URL env variable to support customize mmcv find link

---

mim/cli.py
tests/test_version.py

The `mim --version` command crash in click>=8.x, fix it by pass the \_\_version\_\_ to `version_option`.
- mim/cli.py
- tests/test_version.py
1. Pre-commit or other linting tools …

[Fix] fix mim --version crash in click>=8.x

---

.pre-commit-config.yaml

Update pre-commit config to fix ci.
- .pre-commit-config.yaml

[Chore] Update pre-commit config

---

mim/click/customcommand.py
mim/commands/gridsearch.py
mim/commands/run.py
mim/commands/test.py
mim/commands/train.py
mim/commands/uninstall.py

1.Fix the punctuation display problem on Windows, when running the command `mim run mmdet -h`.
2.Fix the path separator problem on Windows, when running the command `mim run mmdet -h`.
Replace all `Don’t` -> `Don\'t` for problem 1.
In `mim/click/customcommand.py`, '/' -> os.sep for problem 2.

[Fix] Fix the punctuation display problem and the path separator problem on Windows

---

mim/commands/run.py

`mim run mmdet analyze_logs plot_curve .\yolov5_n-v61_syncbn_fast_8xb16-300e_coco_20220919_090739.l  og.json --keys loss_cls --legend loss_cls`
before:
after:
replace all '/' with os.sep in run.py

[Fix] the path separator problem of `mim run` on Windows

---

README.md
mim/commands/download.py
mim/utils/utils.py

Enables to disable ssl certificate checking
Add the option not to check ssl certificate to allow downloads to be performed in environments where ssl errors occur (for example, on-premises)
Some codes have been modified so that the requests module can select whether to check the ssl certificate or not module.
> mim download mmcls **--no-check-certificate** --config resnet18_8xb16_cifar10 --dest .

[Enhancement] Add deactivate SSL certification verity option

---

mim/click/compat.py
mim/utils/utils.py

Fix UserWarning:
```
> mim list
/xxx/lib/python3.8/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
warnings.warn("Setuptools is replacing distutils.")
Package    Version    Source
---------  ---------  --------
```
Use `pip._vendoring.packaging.version` instead of `distutils.version`.
The `pip._vendoring.packaging.version` works fine since `pip>=10.0.0b1` (2018/3/20)

[Fix] fix UserWarning of _distutils_hack

---

mim/utils/utils.py
tests/data/lenet5_mnist_2.0.py
tests/test_gridsearch.py

```bash
mim gridsearch mmcls $CONFIG --work-dir $WORK_DIR --gpus $GPUS \
--search-args --train_dataloader.dataset.pipeline.0.key val1 val2 ...
```
```bash
Traceback (most recent call last):
File "/opt/conda/lib/python3.7/site-packages/mim/commands/gridsearch.py", line 288, in gridsearch
arg_value = get_config(cfg, arg)
File "/opt/conda/lib/python3.7/site-packages/mim/utils/utils.py", line 515, in get_config
assert item in cfg, f'attribute {item} not cfg{suffix}'
AssertionError: attribute 1 not …
```

[Enhance] Add support for sequence input in ``--search-args`` option

---

mim/__init__.py

We could get AssertionError when importing pip before setuptools. A workaround is to import setuptools first and filter warnings that are caused by setuptools replacing distutils.
Fix https://github.com/open-mmlab/mmclassification/issues/1343
Related issues:
- https://github.com/pypa/setuptools/issues/3621
- `mim/__init__.py`

[Fix] Fix AssertionError when importing pip before setuptools

---

mim/click/autocompletion.py

Add missing repos in `get_official_package` to be consistent with 
https://github.com/open-mmlab/mim/blob/2a6adf55cb1382bd2aa5d99a69ab2fa513573083/mim/utils/default.py#L16-L32

[Fix] Add missing repos in `get_official_package`

---

mim/commands/install.py

fixes https://github.com/open-mmlab/mim/issues/210 . I think this bug starts appearing in python 3.11

[Fix] install command should call self.iter_provided_extras method

---

mim/commands/download.py

Support download dataset via openxlab api
1. Pre-commit or other linting tools are used to fix the potential lint …

[Enhance] Support download dataset from openxlab
