- .github/CODE_OF_CONDUCT.md
- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/error-report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/general_questions.md
- .github/pull_request_template.md
This PR adds issue templates and related GitHub documentations.
This PR should be merged after the documentation is online.
> Add github files

- tests/test_gridsearch.py
- tests/test_run.py
- tests/test_test.py
- tests/test_train.py
Fix unittest.
The directory of data in `config.py` is `tmp/dataset`,  so we can not use `tempfile` to create a temporary directory for those unittests.
No BC-breaking
4. The documentation has …
> [Fix] Fix unittest

- mim/commands/install.py
Install mmcv-full from wheel as much as possible instead of compiling from source code
Modify `install.py`
No BC-breaking
4. The documentation has been modified accordingly, like docstring or …
> [Enhancement] Install mmcv-full by fuzzy matching

- docs/conf.py
- mim/version.py
- setup.py
Add version.py
4. The documentation has been modified accordingly, like docstring or example tutorials.
> [Enhancement] Add version.py

- README.md
- setup.py
Rename the package name to openmim and add README.md in pakcage info
4. The documentation has been modified accordingly, like docstring or example tutorials.
> Rename the package name to openmim

- mim/commands/install.py
- tests/test_install.py
Related issue: #29 
Support installing package with editable mode.
No BC-breaking
```bash
git clone https://github.com/open-mmlab/mmclassification.git
cd mmclassification
mim install -e .
```
3. If the modification has potential influence on downstream projects, this PR …
> [Feature] Support installing package with editable mode

- README.md
- mim/commands/install.py
- mim/commands/search.py
- tests/test_search.py
Fix filename of model zoo and output of search command
1. Pre-commit or other linting tools are used to fix the …
> [Fix] Fix filename of model zoo and output of search command

- mim/commands/list.py
- mim/utils/__init__.py
- mim/utils/utils.py
Refactor some helper functions in `utils.py`
1. Pre-commit or other linting tools are used to fix the potential lint …
> [Refactor] Refactor some helper functions in utils.py

- mim/commands/search.py
- tests/test_search.py
Fix error when searching mmsegmentation
1. Pre-commit or other linting tools are used to fix the potential lint …
> [Fix] Fix error when searching mmsegmentation

- mim/utils/utils.py
> [Enhancement] Enhance recursively find

- mim/commands/install.py
Solving issues related to out-of-tree builds. Related issue: https://github.com/pypa/pip/issues/7555
```
DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
```
Please briefly describe what …
> [Fix] Solving issues related to out-of-tree builds

- mim/version.py
> bump version to v0.1.3

- mim/commands/list.py
- mim/utils/utils.py
> [Fix] Fix missing package directory error

- mim/version.py
> bump version to v0.1.4

- .github/workflows/build.yml
Change the version of ubuntu from ubuntu-latest to ubuntu-18.04 in CI
> [Fix] Change ubuntu-latest to ubuntu-18.04

- mim/commands/search.py
Support full match.
- Before the PR
When we type the following command, it will raise an error which is `coco/ap matches [coco/ap, coco/ap@0.5, coco/ap0.75]. However, the number of matched fields should be 1, but got 3`
```
mim search mmpose --dataset coco --sort coco/ap
```
- After the PR
The following command will completely match the `coco/ap`
```
mim search mmpose --dataset coco --sort coco/ap
```
Does the modification introduce changes that break the …
> [Enhancement] Support exact match

- mim/version.py
> bump version to v0.1.5

- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/publish-to-pypi.yml
Cancel the outdated action
- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/publish-to-pypi.yml
1. Pre-commit or other linting tools are used to fix …
> Cancel the outdated action

- .github/workflows/build.yml
- .github/workflows/lint.yml
- .pre-commit-config.yaml
Use official markdownlint hook.
- .github/workflows/build.yml
- .github/workflows/lint.yml
- .pre-commit-config.yaml
1. Pre-commit or other linting tools are used to fix the …
> Use official markdownlint hook

- tests/test_download.py
> [Fix] Update test_download.py

- README.md
Add the link of mmrazor.
2. The …
> [Docs] Add the link of mmrazor

- README.md
- mim/commands/download.py
- tests/test_download.py
Fix the unit test of the download command
- README.md
- mim/commands/download.py
- tests/test_download.py
1. Pre-commit or other linting tools are used to fix the potential lint …
> [Fix] Fix the unit test of the download command

- README.md
Add the link of `mmdeploy`.
Update the `README.md`
2. The modification is covered by complete unit …
> [Docs] Add the link of mmdeploy

- .pre-commit-config.yaml
- mim/__init__.py
- mim/cli.py
- mim/click/__init__.py
- mim/click/autocompletion.py
- mim/click/customcommand.py
- mim/click/option.py
- mim/click/utils.py
- mim/commands/__init__.py
- mim/commands/download.py
- mim/commands/gridsearch.py
- mim/commands/install.py
- mim/commands/list.py
- mim/commands/run.py
- mim/commands/search.py
- mim/commands/test.py
- mim/commands/train.py
- mim/commands/uninstall.py
- mim/utils/__init__.py
- mim/utils/default.py
- mim/utils/utils.py
- tests/test_download.py
- tests/test_gridsearch.py
- tests/test_install.py
- tests/test_list.py
- tests/test_run.py
- tests/test_search.py
- tests/test_test.py
- tests/test_train.py
- tests/test_utils.py
Add copyright pre-commit-hook.
2. …
> Add copyright pre-commit-hook

- README.md
> reorganize readme

- mim/utils/utils.py
Get the version of CUDA properly.
- mim/utils/utils.py
No
4. The documentation has …
> [Fix] Get the version of CUDA properly

- .github/CODE_OF_CONDUCT.md
- .github/ISSUE_TEMPLATE/error-report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/general_questions.md
- .github/pull_request_template.md
- .pre-commit-config.yaml
- README.md
- docs/en/abbreviation.md
- docs/en/installation.md
Replace markdownlint with mdformat to avoid installing ruby. 
Refer to https://github.com/open-mmlab/mmcv/pull/1936
*.md
No
3. If the modification has potential influence on downstream projects, this PR should be tested with …
> [Docs] Replace markdownlint with mdformat for avoiding installing ruby.

- mim/version.py
bump version to v0.1.6
mim/version.py
No
4. The documentation has been modified …
> Bump version to v0.1.6

- .github/workflows/build.yml
- .pre-commit-config.yaml
- docs/en/conf.py
- mim/click/option.py
- mim/commands/install.py
- mim/commands/search.py
- mim/utils/utils.py
- setup.cfg
- setup.py
Add pyupgrade and codespell pre-commit hooks.
1. Pre-commit or other linting tools are used to fix the potential …
> Add pyupgrade and codespell pre-commit hooks

- mim/utils/default.py
Add more packages that support mim to `PKG2PROJECT` in `utils/default.py`.
The follow packages are added to `PKG2PROJECT` :
- mmselfsup
- mmrotate
- mmflow
- ~~mmfewshot~~  (missing .mim)
- ~~mmrazor~~ (missing .mim)
None
None
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream …
> update(PKG2PROJECT): add more packages that support mim

- .github/workflows/build.yml
Add macOS CI.
2. The modification is …
> Add macOS CI

- mim/utils/__init__.py
- mim/utils/progress_bars.py
- mim/utils/utils.py
- requirements/install.txt
Refer to https://github.com/pypa/pip/blob/main/src/pip/_internal/cli/progress_bars.py
Added rich_progress_bar helper function.
1. Pre-commit or other linting tools are used to …
> Add beautiful progressbar

- .github/workflows/publish-to-pypi.yml
- MANIFEST.in
- mim/commands/install.py
- build wheel package when publish to pypi
- include requirements/*.txt when packaging  …
> Fix packaging

- mim/version.py
Bump version to v0.2.1.
mim/version.py
No
4. The documentation has been modified …
> Bump version to v0.2.1

- mim/version.py
Bump version to v0.3.0.
mim/version.py
2. The modification is covered by complete unit tests. If …
> Bump version to v0.3.0

- mim/version.py
Bump version to v0.3.1
- mim/version.py
2. The modification is covered by complete unit tests. If …
> Bump version to v0.3.1

- mim/version.py
> Bump version to v0.3.2

- mim/commands/download.py
- mim/commands/gridsearch.py
Refine error message to tell the user how to install mmengine.
Modifies [the error message in mim](https://github.com/open-mmlab/mim/blob/ffaff8a4ece8a833b20dc7c6c1a7f8647d9eec15/mim/commands/download.py#L92) with:
```
Please install mmengine to use the download command: mim install mmengine.'
```
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility …
> :books: Refine error message to show how to install mmengine.

- mim/utils/default.py
Fix https://github.com/open-mmlab/mim/issues/171
Add `mmyolo` in `PKG2PROJECT`
> [Fix] Add `mmyolo` in `PKG2PROJECT`

- mim/click/customcommand.py
- mim/commands/gridsearch.py
- mim/commands/run.py
- mim/commands/test.py
- mim/commands/train.py
Related to https://github.com/open-mmlab/mim/pull/109, https://github.com/open-mmlab/mim/issues/108
Although the issue when calling `mim install` is resolved in the https://github.com/open-mmlab/mim/pull/132,
but this still exists in other commands such as `mim train` or `mim test`.
Apply the same logic proposed in https://github.com/open-mmlab/mim/pull/109
use `sys.executable` instead of just `'python'`.
If so, please describe how …
> [Enhance] Use sys.executable for calling Python

- mim/commands/run.py
Support running scripts in `demo` dir.
Some scripts for example `boxam_vis_demo.py` in MMYOLO are in `demo` dir.
> [Enhancement] Support running scripts in `demo` dir

- mim/commands/search.py
- tests/test_search.py
Search remote package metadata from PyPI rather than Github to speed up the search command.
Update mim/commands/search.py
1. Pre-commit or other linting tools are used to fix the …
> [Refactor] Search remote package metadata from PyPI rather than Github

- .pre-commit-config.yaml
Upgrade the version of isort to fix lint error.
- .pre-commit-config.yaml
> [Fix] Upgrade the version of isort to fix lint error

- mim/utils/default.py
> Add MMPretrain to the `PKG2PROJECT`.

- mim/version.py
> Bump version to 0.3.7

- mim/version.py
> Bump version to v0.3.8

- mim/version.py
> Bump version to 0.3.9

- mim/version.py
> Bump version to 0.3.10

- mim/commands/install.py
- mim/utils/utils.py
- tests/test_utils.py
> [Fix] Delete version verification of CANN on Ascend NPU
